In [2]:
import numpy as np



In [35]:
a= np.array((1,5,6,3))
a

array([1, 5, 6, 3])

In [31]:
b = np.array([(1.5,6,7),(6,5,9)],dtype=np.int16)
b

array([[1, 6, 7],
       [6, 5, 9]], dtype=int16)

In [34]:
c= np.array([[(1,6,9),(1,5,6)],[(5,6,9),(9,6,8)]])
c

array([[[1, 6, 9],
        [1, 5, 6]],

       [[5, 6, 9],
        [9, 6, 8]]])

In [40]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [44]:
np.arange(10,25,5)

array([10, 15, 20])

In [45]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [46]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [49]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.random.random((2,2))

array([[0.94588498, 0.49863003],
       [0.50637966, 0.90182585]])

In [57]:
np.empty((3,5))

array([[4.67296746e-307, 1.69121096e-306, 1.02361207e-306,
        8.34441742e-308, 1.78022342e-306],
       [6.23058028e-307, 9.79107872e-307, 6.89807188e-307,
        7.56594375e-307, 6.23060065e-307],
       [1.78021527e-306, 8.34454050e-308, 1.11261027e-306,
        2.04712907e-306, 1.34120469e+295]])

In [63]:
a = np.array([(1,2,3),(5,6,7)])
b= np.array([[1,3,6],[5,9,6]])

In [66]:
print(a)
print()
print(b)

[[1 2 3]
 [5 6 7]]

[[1 3 6]
 [5 9 6]]


In [67]:
np.add(a,b)

array([[ 2,  5,  9],
       [10, 15, 13]])

In [68]:
np.subtract(a,b)

array([[ 0, -1, -3],
       [ 0, -3,  1]])

In [69]:
a*b

array([[ 1,  6, 18],
       [25, 54, 42]])

In [70]:
a/b

array([[1.        , 0.66666667, 0.5       ],
       [1.        , 0.66666667, 1.16666667]])

In [71]:
np.sqrt(b)

array([[1.        , 1.73205081, 2.44948974],
       [2.23606798, 3.        , 2.44948974]])

In [72]:
e.dot(f)

NameError: name 'e' is not defined

In [73]:
a==b

array([[ True, False, False],
       [ True, False, False]])

In [74]:
a>b

array([[False, False, False],
       [False, False,  True]])

In [75]:
a.sum()

24

In [76]:
h = a.view()

In [77]:
h

array([[1, 2, 3],
       [5, 6, 7]])

In [80]:
np.copy(a)

array([[1, 2, 3],
       [5, 6, 7]])

In [83]:
n=a.copy()

In [84]:
n

array([[1, 2, 3],
       [5, 6, 7]])

In [85]:
n

array([[1, 2, 3],
       [5, 6, 7]])

In [86]:
print(n)

[[1 2 3]
 [5 6 7]]


In [87]:
n.sort()

In [92]:
a.sort(axis=0)

In [91]:
b

array([[1, 3, 6],
       [5, 6, 9]])

In [96]:
a[1]

array([5, 6, 7])

In [97]:
a[1,1]

6

In [98]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [102]:
a[0:1]

array([[1, 2, 3]])

In [108]:
a[0:1,0:2]

array([[1, 2]])

In [113]:
a[:,1]

array([2, 6])

In [114]:
a[::-1]

array([[5, 6, 7],
       [1, 2, 3]])

In [123]:
for i in range(10,1,-2):
    print(i)

10
8
6
4
2


In [125]:
name = "radar"
a=name[::-1]
print(a)

radar


In [127]:
a

'radar'

In [130]:
a= np.array([[4,5,6],[6,5,3]])
a

array([[4, 5, 6],
       [6, 5, 3]])

In [133]:
a.dtype

dtype('int32')

In [142]:
a.ndim

1

In [143]:
a=np.zeros(10)

In [144]:
a[4]=1

In [145]:
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [148]:
np.random.randint(10,49,size = 10)

array([34, 23, 43, 44, 10, 18, 11, 17, 10, 22])

In [150]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [152]:
a =np.array([1,3,5])
a[::-1]

array([5, 3, 1])

In [153]:
a= np.random.randint(0,8,size=(3,3))

In [154]:
a

array([[3, 6, 2],
       [1, 7, 0],
       [7, 2, 7]])

In [162]:
a=np.arange(0,9)
a
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [164]:
a= np.array([[[1,2,0,0,4,0]]])
a.ndim

3

In [165]:
a[0,0,0]

1

In [166]:
a[0,0,1]

2

In [167]:
a= np.eye(3)

In [168]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [170]:
a= np.random.randint(10,100,size=(10,10))

In [171]:
a

array([[12, 82, 36, 72, 16, 81, 93, 42, 16, 12],
       [29, 76, 13, 39, 32, 82, 94, 19, 96, 87],
       [60, 17, 99, 66, 85, 40, 47, 10, 34, 93],
       [85, 44, 92, 95, 58, 85, 75, 82, 61, 97],
       [42, 82, 13, 42, 89, 28, 59, 17, 72, 93],
       [47, 54, 18, 55, 89, 56, 69, 84, 57, 25],
       [97, 33, 10, 62, 32, 87, 36, 56, 26, 16],
       [47, 58, 75, 52, 10, 94, 53, 58, 48, 47],
       [38, 31, 65, 70, 18, 59, 30, 39, 63, 76],
       [21, 62, 67, 58, 84, 14, 13, 82, 60, 70]])

In [173]:
a.max()

99

In [174]:
a.min()

10

In [188]:
a.max(axis=1)

array([1., 1., 1., 1.])

In [198]:
a=np.ones((4,4))
a[1:3,1:3]=0

a


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [202]:
a=np.ones((4,4))
a[0:4]=0
a[1:3,1:3]=1
a


array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [241]:
a=np.ones((8,8))
a[0::2,1::2]=0
a[1::2,0::2]=0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [229]:
a= np.random.randint(10,100,size=(10))

In [231]:
a.sort()

In [232]:
a

array([21, 32, 37, 48, 60, 62, 63, 71, 82, 84])

In [236]:
c= np.array([(1,3,6,5,2,),(1,6,8,9,5)])

In [240]:

for i in c:
    print(i)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False